name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 5.1.1
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  
  template_string: #^0.6.0
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: template_string