name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
version: 0.15.7
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.5"

dependencies:  
  recase: ^4.1.0
  yaml: ^3.1.1
  equatable: ^2.0.5
  collection: ^1.17.0
  dart_style: ^2.2.4
  logging: ^1.1.0

  flutter:
    sdk: flutter

  template_string: #^0.6.0
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: template_string

dev_dependencies:
  test: ^1.22.1
