name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
version: 0.15.7

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  template_string: #^0.6.0
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: template_string
  
  recase: ^4.0.0
  yaml: ^3.1.1
  equatable: ^2.0.5
  collection: ^1.16.0
  dart_style: ^2.2.3
  logging: ^1.0.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.5
